backend:
  name: git-gateway
  branch: master

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "ニュース"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
